# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GKitExample
 pod 'GKit', :git => 'https://github.com/xiamoweinuan/GKit.git'
 pod 'GKitModel', :git => 'https://github.com/xiamoweinuan/GKitModel.git'
 pod 'GKitGCD', :git => 'https://github.com/xiamoweinuan/GKitGCD.git'
 pod 'GKitComponent', :git => 'https://github.com/xiamoweinuan/GKitComponent.git'

end
